### ISSUE TITLE
内容增加

### ISSUE THREAD

**Issue by peach-water** [AetherIsland/kirara#1]
原神和崩铁都有国际服的，和国服的更新包不同。

因此可以把国际服相关内容也加到项目中吗，感觉在链接部分加上就好了。

**Comment by chenjunyu19** [comment]
**此项目的基本框架还未完成。**

更新包的通道信息将通过配置文件由用户自行配置，但目前没有配置系统，因此在程序入口中硬编码了若干通道用于调试与测试，不代表最终效果。请等待项目正式发布。
