### ISSUE TITLE
老哥, 我看你给minieap提交pr了, 想请教点事情

### ISSUE THREAD

**Issue by huhu415** [AetherIsland/kirara#2]
想请教你点问题, 因为我想重构一下那个minieap, 但我问过作者, 作者说他是代码维护者, 不懂这个项目. 所以我没办法了, 就来这里来请教你了. 我想问点那个minieap的大体思路就行了. 不好意思可能打扰到你了, 因为你的pr的minieap那个项目issues不了, 只能到这里来了

**Comment by chenjunyu19** [comment]
<https://github.com/updateing/minieap/blob/983fd4a5851d4a344fab92666c5cdb83f26b2294/minieap.c#L216>

<https://github.com/updateing/minieap/blob/983fd4a5851d4a344fab92666c5cdb83f26b2294/eap_state_machine.c#L336-L343>

<https://github.com/updateing/minieap/blob/983fd4a5851d4a344fab92666c5cdb83f26b2294/eap_state_machine.c#L295-L308>

<https://github.com/updateing/minieap/blob/983fd4a5851d4a344fab92666c5cdb83f26b2294/eap_state_machine.c#L226-L239>

<https://github.com/updateing/minieap/blob/983fd4a5851d4a344fab92666c5cdb83f26b2294/packet_plugin/packet_plugin.c#L146-L155>

<https://github.com/updateing/minieap/blob/983fd4a5851d4a344fab92666c5cdb83f26b2294/packet_plugin/rjv3/packet_plugin_rjv3.c#L271-L282>
